schemes:
  - CoreMLDemo
  - CoreMLDemoTests

triggers:
  - type: commit
    branchPatterns:
      - "main"

builds:
  - platform: macOS
    configuration: debug
    actions:
      - build
      - test